name = "GPCCData"
uuid = "6ae24528-df3b-47a6-8d0b-c8e9925c8a04"
authors = ["ngiann <ngiann@gmail.com> and contributors"]
version = "0.1.7"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
JLD2 = "0.4"
PyPlot = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
